# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c38c06eb0eda45bf5f0f37eacf403ee6a9b09de55b380586084e30c17785acd90f70891a87c9793ff9e7b13386b818ccd9fdd5a17ba84aaa5cff5827329f4d88

test:
  secret_key_base: e2b3ada49542d05f37ee1a142120c479b2f63316123646a32244bbbae6ae6a50edb142262a4443c9a3c047e9b23959b453e2fc8656bf48bb60116f5b10255e9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
